//! Emit textual LLVM IR for a closure-converted program.
//!
//! Value representation, matching runtime/imprt.h:
//!
//!   * a purell value is one `i64`
//!   * bit 0 set  -> immediate integer, payload is the top 63 bits
//!   * bit 0 clear-> pointer to a closure
//!
//! A closure is laid out as consecutive words: `[0] fn pointer`,
//! `[1] capture count`, `[2..] captured values`. Codegen addresses it as an
//! array of `i64` rather than a named struct so the offsets stay obvious.

use std::fmt::Write;

use crate::core::{Capture, Lam, Program, Term};

const FN_SLOT: usize = 0;
const NFREE_SLOT: usize = 1;
const ENV_BASE: usize = 2;
const WORD: usize = 8;

pub fn emit(program: &Program, module_name: &str) -> String {
    let mut out = String::new();

    writeln!(out, "; module: {module_name}").unwrap();
    writeln!(out, "; generated by impurell").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "; runtime").unwrap();
    writeln!(out, "declare ptr @imp_alloc(i64)").unwrap();
    writeln!(out, "declare void @imp_show_expr(ptr, i64)").unwrap();
    writeln!(out, "declare void @imp_not_a_function(i64) noreturn").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "; primitives").unwrap();
    let mut prims: Vec<&str> = program_primitives(program);
    prims.sort_unstable();
    prims.dedup();
    for symbol in prims {
        writeln!(out, "@{symbol} = external constant i8").unwrap();
    }
    writeln!(out).unwrap();

    writeln!(out, "; source text for the Expr: lines").unwrap();
    for (index, top) in program.tops.iter().enumerate() {
        writeln!(
            out,
            "@imp_src.{index} = private unnamed_addr constant {}",
            c_string(&top.source)
        )
        .unwrap();
    }
    writeln!(out).unwrap();

    for lam in &program.lams {
        emit_lam(&mut out, lam);
    }

    emit_start(&mut out, program);

    writeln!(out).unwrap();
    writeln!(out, "attributes #0 = {{ nounwind }}").unwrap();
    out
}

fn program_primitives(program: &Program) -> Vec<&'static str> {
    let mut found = Vec::new();
    for lam in &program.lams {
        collect_primitives(&lam.body, &mut found);
    }
    for top in &program.tops {
        collect_primitives(&top.term, &mut found);
    }
    found
}

fn collect_primitives(term: &Term, found: &mut Vec<&'static str>) {
    match term {
        Term::Prim(symbol) => found.push(symbol),
        Term::App(left, right) => {
            collect_primitives(left, found);
            collect_primitives(right, found);
        }
        Term::Num(_) | Term::Param | Term::Env(_) | Term::MakeClosure { .. } => {}
    }
}

fn lam_symbol(id: usize) -> String {
    format!("imp_lam.{id}")
}

fn emit_lam(out: &mut String, lam: &Lam) {
    let mut f = FnEmitter::new();
    let result = f.term(&lam.body, Tail::Yes);
    debug_assert!(result.is_none(), "tail emission must have returned");

    writeln!(out, "; \\{}. ...", lam.param).unwrap();
    if !lam.env.is_empty() {
        writeln!(out, "; captures: {}", lam.env.join(", ")).unwrap();
    }
    writeln!(
        out,
        "define internal i64 @{}(ptr %self, i64 %arg) #0 {{",
        lam_symbol(lam.id)
    )
    .unwrap();
    writeln!(out, "entry:").unwrap();
    out.push_str(&f.body);
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_start(out: &mut String, program: &Program) {
    let mut f = FnEmitter::new();

    for (index, top) in program.tops.iter().enumerate() {
        writeln!(f.body, "  ; {}", top.source).unwrap();
        let value = f.term(&top.term, Tail::No).expect("non-tail emission");
        writeln!(
            f.body,
            "  call void @imp_show_expr(ptr @imp_src.{index}, i64 {value})"
        )
        .unwrap();
    }
    writeln!(f.body, "  ret void").unwrap();

    writeln!(out, "define void @imp_start() #0 {{").unwrap();
    writeln!(out, "entry:").unwrap();
    out.push_str(&f.body);
    writeln!(out, "}}").unwrap();
}

#[derive(Clone, Copy, PartialEq)]
enum Tail {
    Yes,
    No,
}

struct FnEmitter {
    body: String,
    next_reg: usize,
    next_label: usize,
}

impl FnEmitter {
    fn new() -> Self {
        FnEmitter {
            body: String::new(),
            next_reg: 0,
            next_label: 0,
        }
    }

    fn reg(&mut self) -> String {
        self.next_reg += 1;
        format!("%v{}", self.next_reg)
    }

    fn label(&mut self) -> usize {
        self.next_label += 1;
        self.next_label
    }

    /// Emit `term`. Returns the operand holding its value, or `None` when
    /// `tail` was `Yes` and the function has already returned.
    fn term(&mut self, term: &Term, tail: Tail) -> Option<String> {
        // Only an application can be emitted as a real tail call; everything
        // else falls back to computing a value and returning it.
        if let (Tail::Yes, Term::App(left, right)) = (tail, term) {
            let f = self.term(left, Tail::No).expect("non-tail emission");
            let x = self.term(right, Tail::No).expect("non-tail emission");
            self.apply(&f, &x, Tail::Yes);
            return None;
        }

        let value = match term {
            Term::Num(n) => tagged_number(*n),
            Term::Prim(symbol) => {
                let dst = self.reg();
                writeln!(self.body, "  {dst} = ptrtoint ptr @{symbol} to i64").unwrap();
                dst
            }
            Term::Param => "%arg".to_string(),
            Term::Env(index) => self.load_env(*index),
            Term::MakeClosure { lam, captures } => self.make_closure(*lam, captures),
            Term::App(left, right) => {
                let f = self.term(left, Tail::No).expect("non-tail emission");
                let x = self.term(right, Tail::No).expect("non-tail emission");
                self.apply(&f, &x, Tail::No).expect("non-tail application")
            }
        };

        if tail == Tail::Yes {
            writeln!(self.body, "  ret i64 {value}").unwrap();
            return None;
        }
        Some(value)
    }

    fn load_env(&mut self, index: usize) -> String {
        let slot = self.reg();
        writeln!(
            self.body,
            "  {slot} = getelementptr inbounds i64, ptr %self, i64 {}",
            ENV_BASE + index
        )
        .unwrap();
        let dst = self.reg();
        writeln!(self.body, "  {dst} = load i64, ptr {slot}").unwrap();
        dst
    }

    fn make_closure(&mut self, lam: usize, captures: &[Capture]) -> String {
        // Capture values are read from the current frame *before* the
        // allocation, which keeps the reads independent of the store order.
        let values: Vec<String> = captures
            .iter()
            .map(|capture| match capture {
                Capture::Param => "%arg".to_string(),
                Capture::Env(index) => self.load_env(*index),
            })
            .collect();

        let size = (ENV_BASE + captures.len()) * WORD;
        let clo = self.reg();
        writeln!(self.body, "  {clo} = call ptr @imp_alloc(i64 {size})").unwrap();
        writeln!(
            self.body,
            "  store ptr @{}, ptr {clo}",
            lam_symbol(lam)
        )
        .unwrap();
        debug_assert_eq!(FN_SLOT, 0, "fn pointer is stored at offset zero");

        let nfree_slot = self.reg();
        writeln!(
            self.body,
            "  {nfree_slot} = getelementptr inbounds i64, ptr {clo}, i64 {NFREE_SLOT}"
        )
        .unwrap();
        writeln!(
            self.body,
            "  store i64 {}, ptr {nfree_slot}",
            captures.len()
        )
        .unwrap();

        for (index, value) in values.iter().enumerate() {
            let slot = self.reg();
            writeln!(
                self.body,
                "  {slot} = getelementptr inbounds i64, ptr {clo}, i64 {}",
                ENV_BASE + index
            )
            .unwrap();
            writeln!(self.body, "  store i64 {value}, ptr {slot}").unwrap();
        }

        let dst = self.reg();
        writeln!(self.body, "  {dst} = ptrtoint ptr {clo} to i64").unwrap();
        dst
    }

    /// Apply `f` to `x`, trapping if `f` turned out to be a number.
    fn apply(&mut self, f: &str, x: &str, tail: Tail) -> Option<String> {
        let id = self.label();
        let tag = self.reg();
        let is_closure = self.reg();

        writeln!(self.body, "  {tag} = and i64 {f}, 1").unwrap();
        writeln!(self.body, "  {is_closure} = icmp eq i64 {tag}, 0").unwrap();
        writeln!(
            self.body,
            "  br i1 {is_closure}, label %apply.{id}, label %notfn.{id}"
        )
        .unwrap();

        writeln!(self.body, "notfn.{id}:").unwrap();
        writeln!(self.body, "  call void @imp_not_a_function(i64 {f})").unwrap();
        writeln!(self.body, "  unreachable").unwrap();

        writeln!(self.body, "apply.{id}:").unwrap();
        let clo = self.reg();
        writeln!(self.body, "  {clo} = inttoptr i64 {f} to ptr").unwrap();
        let fn_ptr = self.reg();
        writeln!(self.body, "  {fn_ptr} = load ptr, ptr {clo}").unwrap();
        debug_assert_eq!(FN_SLOT, 0, "fn pointer is loaded from offset zero");

        let dst = self.reg();
        let kind = match tail {
            // musttail is a guarantee, not a hint: combinator-driven recursion
            // runs in constant stack space even at -O0.
            Tail::Yes => "musttail call",
            Tail::No => "call",
        };
        writeln!(
            self.body,
            "  {dst} = {kind} i64 {fn_ptr}(ptr {clo}, i64 {x})"
        )
        .unwrap();

        if tail == Tail::Yes {
            writeln!(self.body, "  ret i64 {dst}").unwrap();
            return None;
        }
        Some(dst)
    }
}

/// `(n << 1) | 1`. The parser has already checked that `n` fits in 63 bits.
fn tagged_number(n: i64) -> String {
    (n.wrapping_shl(1) | 1).to_string()
}

/// Render a Rust string as an LLVM `[N x i8] c"..."` constant, NUL-terminated.
fn c_string(text: &str) -> String {
    let bytes = text.as_bytes();
    let mut escaped = String::new();
    for &byte in bytes {
        // LLVM string literals only take `\XX` escapes; `"` and `\` must use
        // them too.
        if byte.is_ascii_graphic() && byte != b'"' && byte != b'\\' || byte == b' ' {
            escaped.push(byte as char);
        } else {
            write!(escaped, "\\{byte:02X}").unwrap();
        }
    }
    format!("[{} x i8] c\"{escaped}\\00\"", bytes.len() + 1)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::Converter;
    use crate::lexer;

    fn compile(source: &str) -> String {
        let expr = lexer::parse_expr(source).expect("parses");
        let mut converter = Converter::new();
        let top = converter.convert_top(source, &expr).expect("converts");
        emit(&converter.finish(vec![top]), "test")
    }

    #[test]
    fn literals_are_tagged() {
        assert_eq!(tagged_number(0), "1");
        assert_eq!(tagged_number(1), "3");
        assert_eq!(tagged_number(-1), "-1");
        assert_eq!(tagged_number(42), "85");
    }

    #[test]
    fn backslashes_in_source_are_escaped() {
        let literal = c_string("\\x.x");
        assert_eq!(literal, "[5 x i8] c\"\\5Cx.x\\00\"");
    }

    #[test]
    fn tail_application_uses_musttail() {
        let ir = compile("\\f.\\x.f x");
        assert!(ir.contains("musttail call"), "{ir}");
    }

    #[test]
    fn top_level_shows_each_expression() {
        let ir = compile("42");
        assert!(ir.contains("@imp_show_expr(ptr @imp_src.0, i64 85)"), "{ir}");
    }
}
